export const INTERESTS = [
  { id: 1, content: "운동" },
  { id: 2, content: "산책" },
  { id: 3, content: "노래" },
  { id: 4, content: "술" },
  { id: 5, content: "헬스" },
  { id: 6, content: "패션" },
  { id: 7, content: "영화" },
  { id: 8, content: "공부" },
  { id: 9, content: "연극" },
  { id: 10, content: "화장" },
  { id: 11, content: "전시회" },
  { id: 12, content: "맛집투어" },
  { id: 13, content: "보드게임" },
  { id: 14, content: "자기관리" },
];

export const MBTIS = [
  { id: 1, content: "INFP" },
  { id: 2, content: "ENFP" },
  { id: 3, content: "INFJ" },
  { id: 4, content: "ENFJ" },
  { id: 5, content: "INTJ" },
  { id: 6, content: "ENTJ" },
  { id: 7, content: "INTP" },
  { id: 8, content: "ENTP" },
  { id: 9, content: "ISFP" },
  { id: 10, content: "ESFP" },
  { id: 11, content: "ISTP" },
  { id: 12, content: "ESTP" },
  { id: 13, content: "ISFJ" },
  { id: 14, content: "ESFJ" },
  { id: 15, content: "ISTJ" },
  { id: 16, content: "ESTJ" },
];
